version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.10.3
    container_name: "igata-localstack-0.10.3"
    ports:
      - "4567-4593:4567-4593"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb

  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
    environment:
      - TARGETS=localstack:4572,localstack:4575
