version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.13.1
    container_name: "igata-localstack-0.13.1"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb

  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
    environment:
      - TARGETS=localstack:4566
