version: 2

jobs:
  build:
    working_directory: ~/app/
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: localstack/localstack:0.10.3

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Upgrade pipenv
          command: |
            pip install pipenv -U
      - run:
          name: install dependencies
          command: |
            pipenv sync --dev
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/home/circleci/.aws"
            - "/home/circlci/.local"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: prepare boto3 credentials and awscli
          command: |
            # install envsubst (provided by gettext-base)
            sudo apt install gettext-base

            # for deployment
            pip install awscli

            # prepare credentials
            mkdir -p ~/.aws
            cat ./infrastructure/aws/awscli/credentials.template | envsubst > ~/.aws/credentials
            cat ./infrastructure/aws/awscli/config.template | envsubst > ~/.aws/config
            # test aws cli
            # >>> commenting out since localstack is used and deployment not needed atm.
            #aws sts get-caller-identity
      - run:
          name: run tests
          command: |
            make test
      - run:
          name: code checks (flake8)
          command: |
            make flake8


workflows:
  version: 2
  test-deploy:
    jobs:
      - build

