FROM ubuntu:18.04

MAINTAINER Developers <developers@kiconiaworks.com>

# resolves tzdata configuration issue
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y git libopencv-dev libopenblas-dev
RUN apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

# install pyenv to build python
RUN curl https://pyenv.run | bash

SHELL ["/bin/bash", "-c"]

ENV PATH "/root/.pyenv/shims:/root/.pyenv/bin:$PATH"

RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
RUN echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
RUN echo 'export PATH="/root/.pyenv/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
RUN source ~/.bashrc

RUN pyenv update
RUN pyenv install 3.7.2
RUN pyenv global 3.7.2

RUN python3.7 -m pip install pip -U && python3.7 -m pip install wheel
RUN python3.7 -m pip install pipenv

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# update shims after package install to refresh path!
RUN pyenv rehash

#変更がありそうな箇所
## ??? DEFINE envars to determine input/output usage?
## igata should wrap and find the predictor

# this command is defined in terraform and run for on batch execution!!!!
## docker run imagename pipenv run igata.runner.cli

COPY . /app

RUN cd /app && pipenv sync

WORKDIR /app

