"""
Project/package-wide settings
"""
import logging
import os

logger = logging.getLogger(__name__)


MAX_POST_IMAGES = 50
AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-northeast-1")

DEFAULT_S3_ENDPOINT = f"https://s3.{AWS_REGION}.amazonaws.com"
S3_ENDPOINT = os.getenv("S3_ENDPOINT", DEFAULT_S3_ENDPOINT)

DEFAULT_SQS_ENDPOINT = f"https://sqs.{AWS_REGION}.amazonaws.com"
SQS_ENDPOINT = os.getenv("SQS_ENDPOINT", DEFAULT_SQS_ENDPOINT)

DEFAULT_SNS_ENDPOINT = f"https://sns.{AWS_REGION}.amazonaws.com"
SNS_ENDPOINT = os.getenv("SNS_ENDPOINT", DEFAULT_SNS_ENDPOINT)

DEFAULT_DYNAMODB_ENDPOINT = f"https://dynamodb.{AWS_REGION}.amazonaws.com"
DYNAMODB_ENDPOINT = os.getenv("DYNAMODB_ENDPOINT", DEFAULT_DYNAMODB_ENDPOINT)

DEFAULT_DYNAMODB_DECIMAL_PRECISION_DIGITS = "6"
DYNAMODB_DECIMAL_PRECISION_DIGITS = int(os.getenv("DYNAMODB_DECIMAL_PRECISION_DIGITS", DEFAULT_DYNAMODB_DECIMAL_PRECISION_DIGITS))

DEFAULT_SQS_VISIBILITYTIMEOUT_SECONDS_ON_EXCEPTION = "5"
SQS_VISIBILITYTIMEOUT_SECONDS_ON_EXCEPTION = int(
    os.getenv("SQS_VISIBILITYTIMEOUT_SECONDS_ON_EXCEPTION", DEFAULT_SQS_VISIBILITYTIMEOUT_SECONDS_ON_EXCEPTION)
)

DEFAULT_CSV_DIALECT = "excel"
CSV_DIALECT = os.getenv("CSV_DIALECT", DEFAULT_CSV_DIALECT)

DOWNLOAD_WORKERS = int(os.getenv("DOWNLOAD_WORKERS", 8))

# comma separated
DEFAULT_S3URI_KEYS = "s3_uri"
REQUEST_S3URI_KEYS = os.getenv("REQUEST_S3URI_KEYS", DEFAULT_S3URI_KEYS)
if REQUEST_S3URI_KEYS:
    REQUEST_S3URI_KEYS = REQUEST_S3URI_KEYS.split(",")

DEFAULT_MAX_PROCESSING_REQUESTS = 50
MAX_PROCESSING_REQUESTS = int(os.getenv("MAX_PROCESSING_REQUESTS", str(DEFAULT_MAX_PROCESSING_REQUESTS)))
logger.info(f"(ENVAR) MAX_PROCESSING_REQUESTS: {MAX_PROCESSING_REQUESTS}")

DEFAULT_MAX_PER_REQUEST_PROCESSING_SECONDS = 60
MAX_PER_REQUEST_PROCESSING_SECONDS = int(os.getenv("MAX_PER_REQUEST_PROCESSING_SECONDS", str(DEFAULT_MAX_PER_REQUEST_PROCESSING_SECONDS)))
logger.info(f"MAX_PER_REQUEST_PROCESSING_SECONDS: {MAX_PER_REQUEST_PROCESSING_SECONDS}")
