"""
Project/package-wide settings
"""
import os

MAX_POST_IMAGES = 50
AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-northeast-1")

DEFAULT_S3_ENDPOINT = f"https://s3.{AWS_REGION}.amazonaws.com"
S3_ENDPOINT = os.getenv("S3_ENDPOINT", DEFAULT_S3_ENDPOINT)

DEFAULT_SQS_ENDPOINT = f"https://sqs.{AWS_REGION}.amazonaws.com"
SQS_ENDPOINT = os.getenv("SQS_ENDPOINT", DEFAULT_SQS_ENDPOINT)

DEFAULT_SNS_ENDPOINT = f"https://sns.{AWS_REGION}.amazonaws.com"
SNS_ENDPOINT = os.getenv("SNS_ENDPOINT", DEFAULT_SNS_ENDPOINT)

DEFAULT_DYNAMODB_ENDPOINT = f"https://dynamodb.{AWS_REGION}.amazonaws.com"
DYNAMODB_ENDPOINT = os.getenv("DYNAMODB_ENDPOINT", DEFAULT_DYNAMODB_ENDPOINT)

DEFAULT_DYNAMODB_DECIMAL_PRECISION_DIGITS = "6"
DYNAMODB_DECIMAL_PRECISION_DIGITS = int(os.getenv("DYNAMODB_DECIMAL_PRECISION_DIGITS", DEFAULT_DYNAMODB_DECIMAL_PRECISION_DIGITS))
